do $$ declare actor uuid:='10000000-0000-4000-8000-0000000000a1'; r jsonb; lease jsonb; newer jsonb; out jsonb; a uuid; c uuid; body jsonb:='{"from":"test@example.invalid","to":["invite@example.invalid"],"reply_to":"test@example.invalid","subject":"Frozen","html":"Frozen","text":"Frozen"}'; begin
 r:=public.create_client_with_request(actor,'a0000000-0000-4000-8000-000000000011','boundary','{"name":"Boundary","email":"invite@example.invalid","coach_id":"10000000-0000-4000-8000-0000000000a1","invite_now":true}',body); a:=(r->>'attempt_id')::uuid; c:=(r->'client'->>'id')::uuid;
 lease:=public.admit_invite_call(actor,a);
 update public.client_invite_attempts set lease_expires_at=clock_timestamp()-interval '1 second' where id=a;
 newer:=public.admit_invite_call(actor,a);
 perform pg_temp.check(newer->>'admitted'='true' and newer->'provider_body'=body,'expired lease preserves frozen body');
 out:=public.complete_invite_call(a,(lease->>'lease_token')::uuid,'{"kind":"accepted","provider_message_id":"c0000000-0000-4000-8000-000000000011"}');
 perform pg_temp.check(out->>'status'='unknown','stale completion fenced');
 out:=public.complete_invite_call(a,(newer->>'lease_token')::uuid,'{"kind":"rejected","code":"validation_error"}');
 perform pg_temp.check(out->>'status'='unknown' and out->>'retryable'='false' and out->>'needs_confirmation'='true','later rejection cannot settle uncertainty');
 out:=public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000011','resend',a,false,body);
 perform pg_temp.check(out->'result'->>'outcome'='needs_confirmation','new key requires confirmation');
 out:=public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000012','resend',a,true,body); a:=(out->>'attempt_id')::uuid;
 lease:=public.admit_invite_call(actor,a);
 update public.client_invite_attempts set lease_expires_at=clock_timestamp()-interval '1 second' where id=a;
 newer:=public.admit_invite_call(actor,a);
 out:=public.complete_invite_call(a,(newer->>'lease_token')::uuid,'{"kind":"accepted","provider_message_id":"c0000000-0000-4000-8000-000000000012"}');
 perform pg_temp.check(out->>'status'='accepted' and out->>'needs_confirmation'='false','acceptance settles all prior uncertainty');
 update public.client_invite_attempts set first_provider_call_at=clock_timestamp()-interval '23 hours' where id=a;
 out:=public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000013','resend',a,false,body);
 perform pg_temp.check(out->'result'->>'outcome'='selected','accepted prior crash does not require risk confirmation'); a:=(out->>'attempt_id')::uuid;
 update public.client_invite_attempts set first_provider_call_at=clock_timestamp()-interval '22 hours 59 minutes' where id=a;
 lease:=public.admit_invite_call(actor,a); perform pg_temp.check(lease->>'admitted'='true','22:59 admitted');
 perform public.complete_invite_call(a,(lease->>'lease_token')::uuid,'{"kind":"unknown","code":"timeout"}');
 update public.client_invite_attempts set first_provider_call_at=clock_timestamp()-interval '23 hours' where id=a;
 out:=public.admit_invite_call(actor,a); perform pg_temp.check(out->>'admitted'='false' and out->'invite'->>'needs_confirmation'='true','23:00 blocks same-key admission');
 perform pg_temp.check((select provider_body is null from public.client_invite_attempts where id=a),'cutoff redacts frozen body');
 out:=public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000014','resend',null,true,body);
 perform pg_temp.check(out->'result'->>'outcome'='stale','confirmation must bind latest attempt');
 out:=public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000015','resend',a,true,body);
 lease:=public.admit_invite_call(actor,(out->>'attempt_id')::uuid);
 perform public.apply_invite_action(actor,c,'b0000000-0000-4000-8000-000000000016','switch_off',null,false,null);
 out:=public.complete_invite_call((out->>'attempt_id')::uuid,(lease->>'lease_token')::uuid,'{"kind":"accepted","provider_message_id":"c0000000-0000-4000-8000-000000000013"}');
 perform pg_temp.check(out->>'status'='accepted' and not (select invited from public.clients where id=c),'admitted-before-off acceptance does not restore claim permission');
end $$;
