from pathlib import Path
import json,base64,html,sys
repo=Path(__file__).resolve().parents[2]
d=repo/'docs/workout-ux-visual-review'
out=Path(sys.argv[1]).resolve()
out.mkdir(parents=True,exist_ok=True)
m=json.loads((d/'manifest.json').read_text())
pages=[
('weight','Decimal loads fit the phone','At 320px, the baseline document is 352px wide and leaves 10px for 38.26px of weight text. After: 320px document, 106px usable input width. Weight and unit occupy their own row; reps, RPE and completion sit below. Finish actions wrap inside the controls at the end of the workout.'),
('builder-top','Workout editor fits; labels persist','The narrow editor previously had a 588px content width. After: 318px at 320px viewport and 388px at 390px. Workout day, exercise and numeric fields have durable visible labels. Long names are contained. Same populated expanded exercise, editor at top.'),
('builder-lower','Authoring fields and lower actions','The same internal-note field is anchored within the scrollable editor. Labels remain visible after entry. Unit, notes and scoped authoring actions use the existing styling and 44px controls. Different content heights require different numeric scroll offsets.'),
('builder-targets','Duration and distance targets remain explicit','Identical synthetic targets: Duration + distance, 20 min and 3 km. Typed tracking and unit behavior were already released in the baseline and remain unchanged. The responsive editor now contains the surrounding exercise fields. Targets are coach instructions; actual values start blank.'),
('rest-controls','Rest and finish controls remain reachable','Same running 60-second rest, document scrolled to the end. The timer, −15 / +15 and finish actions remain available with unchanged timer behavior. After: controls stay in normal document flow below the exercises; they no longer remain pinned while scrolling. This removes the overlay rather than hiding content or shrinking targets.'),
('validation','Invalid entries have adjacent errors','Same RPE 11, blurred, with no write. The baseline shows its existing toast. After also shows an adjacent error associated with the RPE input through aria-invalid and aria-describedby. The original toast remains. Validation limits are unchanged.'),
('touch-targets','Workout start and PDF controls','Same assigned standalone workout, before any start or download action. Start workout and workout PDF controls increase from 32px to 44px high. Their labels and behavior remain unchanged. Existing navigation is retained.'),
('rest-overlay','Previously obscured exercise actions are clear','After: Add set and Same as last time are fully visible and pass all nine hit-test points at scrollY 571 (320px) and 271 (390px), with rest running. Before: Same as last time fails hit-testing. At 390px the baseline clamps at page top: actual control y633 rather than requested y650; After reaches y650. Exact offsets and rectangles are recorded in the manifest.'),
('desktop','Desktop sanity: tracker and authoring','1440 × 900: tracker keeps its desktop row arrangement with usable load/reps/RPE columns; the editor retains the existing two-pane layout and adds persistent labels. Same populated exercise and top/weight anchor as the phone captures.')]
css='''*{box-sizing:border-box}body{margin:0;background:#e9edf0;color:#14212b;font:14px Arial,sans-serif}.sheet{width:1120px;margin:24px auto;padding:28px;background:white;break-after:page}.sheet:last-child{break-after:auto}h1{font-size:22px;margin:0 0 6px}p{margin:6px 0;line-height:1.35}.meta{font-size:11px;color:#475569}.hold{font-weight:bold;color:#914600}.groups{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:12px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:8px}.frame{text-align:center;margin:0}.frame figcaption{font-size:12px;font-weight:bold;margin:0 0 6px}.frame img{display:block;max-width:100%;height:540px;object-fit:contain;object-position:top;background:#f4f5f6;margin:auto}.group-title{font-size:13px;margin:0 0 6px}.footer{margin-top:10px;font-size:10px;color:#475569}.desktop .groups{grid-template-columns:1fr;gap:10px}.desktop .frame img{height:260px}.appendix{width:1120px;margin:24px auto;background:white;padding:28px}.appendix details{margin:12px 0}.appendix img{max-width:100%;height:auto}a{color:#126477}code{font-size:10px;overflow-wrap:anywhere}@page{size:A4 landscape;margin:9mm}@media print{body{background:white;font-size:9pt}.sheet{width:279mm;height:191mm;margin:0;padding:0;overflow:hidden}h1{font-size:15pt}p{font-size:8.2pt}.meta{font-size:7pt}.groups{gap:5mm;margin-top:3mm}.frame figcaption{font-size:8pt}.frame img{height:139mm;max-width:65mm}.group-title{font-size:8pt}.footer{font-size:6.3pt;margin-top:2mm}.desktop .frame img{height:64mm;max-width:135mm}.desktop .groups{gap:3mm}.appendix{display:none}}'''
def build(embed=False):
 def image_ref(f):return 'data:image/png;base64,'+base64.b64encode((d/f).read_bytes()).decode() if embed else f
 def group(scene,w):
  records=[next(c for c in m['captures'] if c['scene']==scene and c['width']==w and c['version']==v) for v in ('before','after')]
  h=records[0]['height'];frames=''
  for c in records:
   version=c['version'];scroll=f'<br>scrollY {c["screen"]["scrollY"]} · '+(f'action y{c["detail"]["actualControlTop"]}' if 'actualControlTop' in c['detail'] else 'document bottom') if scene.startswith('rest') else '';links='' if embed else f'<a href="{c["file"]}">PNG</a>'
   frames+=f'<figure class="frame"><figcaption>{version.title()} · {m["sources"][version]["sha"][:8]} {links}{scroll}</figcaption><img src="{image_ref(c["file"])}" alt="{html.escape(scene)} {w} {version}"></figure>'
  return f'<div><h2 class="group-title">{scene if w==1440 else "Phone"} · {w} × {h}</h2><div class="pair">{frames}</div></div>'
 sections=[]
 for n,(scene,title,caption) in enumerate(pages,1):
  groups=group('weight',1440)+group('builder-top',1440) if scene=='desktop' else group(scene,320)+group(scene,390)
  sections.append(f'<section class="sheet {"desktop" if scene=="desktop" else ""}"><h1>{n}. {title}</h1><p>{caption}</p><p class="meta">Actual Chromium renders · identical synthetic data · dark theme · reduced motion · UTC · requested logical anchors; actual scroll offsets recorded</p><p class="meta hold">LOCAL REVIEW ONLY — publication and merge on hold for owner visual review.</p><div class="groups">{groups}</div><div class="footer">Before: {m["sources"]["before"]["sha"]} · After UI capture: {m["sources"]["after"]["sha"]}<br>D7: controls remain in document flow and are no longer pinned. Timer behavior and typed logging unchanged. Fixture API interception proves frontend behavior, not live persistence/auth. No real client data. Phone keyboard, physical Safari/PWA and deferred optimistic detail snapshot are unverified. Page {n}/{len(pages)}.</div></section>')
 appendix='<section class="appendix"><h1>Evidence and full context</h1><p>Each page preserves the entire viewport including navigation, toast and dock. Links below retain additional full-page context; full-page captures change the screenshot extent, not the paired viewport evidence. Actual scroll offsets, source SHA, image hashes, measurements and interception results are in manifest.json.</p>'
 if embed:appendix+='<details><summary>Capture manifest</summary><pre>'+html.escape(json.dumps(m,indent=2))+'</pre></details>'
 else:appendix+='<p><a href="manifest.json">Capture manifest</a> · <a href="README.md">Review notes and reproduction</a></p>'
 for c in m['captures']:
  for f in c['fullContext']:appendix+=f'<details><summary>{c["scene"]} · {c["width"]} · {c["version"]} · full context</summary><img src="{image_ref(f)}" alt="Full context {c["scene"]} {c["version"]}"></details>'
 appendix+='</section>'
 return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CVF PT workout UI — actual before and after</title><style>'+css+'</style><body>'+''.join(sections)+appendix+'</body></html>'
(d/'index.html').write_text(build())
(out/'CVFPT-Workout-UI-Before-After.html').write_text(build(True))
print('Wrote repository HTML and portable HTML',len(m['captures']),'viewport captures')
